name: Pipeline for automation tests

on: 
 push: 
   branches: 
       master

jobs:
  build:
    runs-on: windows-latest
    
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 8
        uses: actions/setup-java@v2
        with:
          java-version: '8'
          distribution: 'adopt'
      - name: Run automation tests for web application
        run: mvn clean test -Dsuite=web
