name: Pipeline for automation tests

on: 
 push: 
   branches: 
       master

jobs:
  build:
    runs-on: windows-latest
    
    steps:
      - uses: actions/checkout@v2
      
      - name: Set up JDK 8
        uses: actions/setup-java@v2
        with:
          java-version: '8'
          distribution: 'adopt'
          ca—Åhe: maven
      - run: mvn clean test -Dsuite=web
      
      - name: Allure report generation
      - run: mvn allure:report
      
      - name: Upload allure report artifact
        uses: actions/upload-artifact@v2
        with:
          name: allure-report
          path: target/site/allureReport
